#!/usr/bin/env python3
"""Makes port/src/main/pc_font.h, the fonts of the settings window
(pc_launcher.c): DejaVu Sans drawn once at two sizes, each glyph cropped
and stored with 16 levels of coverage, one hex digit per pixel.

    python3 port/tools/make_font.py /usr/share/fonts/truetype/dejavu > port/src/main/pc_font.h

Needs Pillow (pip install pillow). Only to change the fonts: the header is
in the repository.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

EXTRA = "…✓✗◀▶•—’←↑→↓✕○□△Œœ"
TEXT = [chr(c) for c in range(32, 127)] + [chr(c) for c in range(160, 256)] + list(EXTRA)
TITLE = [chr(c) for c in range(32, 127)] + [chr(c) for c in range(192, 256)]


def font(name, path, size, chars):
    f = ImageFont.truetype(path, size)
    ascent, descent = f.getmetrics()
    glyphs, pixels = [], []
    for ch in chars:
        advance = round(f.getlength(ch))
        box = f.getbbox(ch)
        w, h = max(box[2] - box[0], 0), max(box[3] - box[1], 0)
        offset = sum(len(p) for p in pixels)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-box[0], -box[1]), ch, font=f, fill=255)
            data = img.tobytes()
            pixels.append("".join("%x" % ((v * 15 + 127) // 255) for v in data))
        else:
            w = h = 0
        glyphs.append((ord(ch), box[0] if w else 0, box[1] if h else 0, w, h, advance, offset))
    out = []
    out.append("static const FontGlyph %s_glyphs[] = {" % name)
    for g in glyphs:
        out.append("    { 0x%04x, %d, %d, %d, %d, %d, %d }," % g)
    out.append("};")
    text = "".join(pixels)
    out.append("static const char %s_pixels[] =" % name)
    for i in range(0, len(text), 96):
        out.append('    "%s"' % text[i:i + 96])
    out.append("    ;")
    out.append("static const Font %s = { %s_glyphs, sizeof(%s_glyphs) / sizeof(%s_glyphs[0]), %s_pixels, %d, %d };"
               % (name, name, name, name, name, ascent + descent, ascent))
    return "\n".join(out)


def main():
    folder = sys.argv[1]
    print("/*")
    print(" * Generated by port/tools/make_font.py: DejaVu Sans, 17 px, and DejaVu Sans")
    print(" * Bold, 28 px, for the settings window. Each glyph: code point, offset of")
    print(" * its box from the pen (x) and from the top of the line (y), size, advance,")
    print(" * and where its pixels start in the string (one hex digit of coverage each).")
    print(" *")
    print(" * DejaVu fonts: Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved.")
    print(" * Bitstream Vera is a trademark of Bitstream, Inc. DejaVu changes are in")
    print(" * the public domain. Permission is granted to use, copy, modify and")
    print(" * distribute the Font Software under the Bitstream Vera license")
    print(" * (https://dejavu-fonts.github.io/License.html); this rendering is not")
    print(" * named Bitstream or Vera.")
    print(" */")
    print("typedef struct {")
    print("    unsigned short code;")
    print("    signed char x, y;")
    print("    unsigned char w, h, advance;")
    print("    int offset;")
    print("} FontGlyph;")
    print("typedef struct {")
    print("    const FontGlyph *glyphs;")
    print("    int count;")
    print("    const char *pixels;")
    print("    int height, ascent;")
    print("} Font;")
    print(font("font_text", os.path.join(folder, "DejaVuSans.ttf"), 17, TEXT))
    print(font("font_title", os.path.join(folder, "DejaVuSans-Bold.ttf"), 28, TITLE))


main()
